#! /bin/sh -e

case "$1" in
configure)
	if ! getent group | grep -q "^stapdev:"; then
		echo "Adding stapdev group..."
		addgroup --quiet --system stapdev || true
	fi
	if ! getent group | grep -q "^stapusr:"; then
		echo "Adding stapusr group..."
		addgroup --quiet --system stapusr || true
	fi
	;;
abort-upgrade|abort-remove|abort-deconfigure)
	;;
*)
	echo "$0 called with unknown argument '$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#
