set test "input.line"
set send_human { .1 .3 1 .05 2 }

spawn stap $srcdir/$subdir/$test.stp
expect

send -raw "abcde\n"

expect {
        "abcde\r\n"  { pass "ok" }
        timeout { fail "(timeout)" }
}

send -h -raw "123456789"

expect {
        -re .+ { fail "unexpected output"}
        timeout { pass "ok" }
}

send -raw "\n"

expect {
        "123456789\r\n" { pass "ok" }
        timeout { fail "(timeout)" }
}

kill -INT -[exp_pid] 3
catch {close}; catch {wait}
