set test_file_name "try_assign"
set test test_file_name

if {! [installtest_p]} { untested $test_file_name; return }

foreach runtime [get_runtime_list] {
    if {$runtime != ""} {
        lappend test "($runtime)"
        stap_run $test no_load $all_pass_string \
        --runtime=$runtime $srcdir/$subdir/$test_file_name.stp 
    } else {
        stap_run $test no_load $all_pass_string $srcdir/$subdir/$test_file_name.stp 
    }
}



